import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Header } from '@/components/layouts/header';
import { Sidebar } from '@/components/layouts/sidebar/sidebar';

import { cn } from '../lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'relative flex h-screen w-screen')}>
        <Sidebar />
        <Header />
        <div className="no-scrollbar container flex w-full justify-center overflow-x-hidden pl-20 pt-20 lg:pl-56 xl:pl-40">
          {children}
        </div>
      </body>
    </html>
  );
}
